package de.my.tcg.game.mate.card.retreat;

public enum PerformRetreatState {

    CAN_NOT_RETREAT_DUE_TO_CANNOT_AFFORT_COSTS,
    CAN_NOT_RETREAT_DUE_TO_EMPTY_BENCH,
    SELECTED_BENCHMON_IS_NOT_THERE,
    CAN_NOT_RETREAT_DUE_TO_STATUSCONDITION,
    CAN_NOT_RETREAT_DUE_TO_TURNEFFECT,
    ENERGY_SELECTION_NEEDED,
    ERROR,
    EXCHANGE_SUCCESSFULL

}
